### ISSUE TITLE
indent/outdent mismatch: 1

### ISSUE THREAD

**Issue by glorious1** [hermanbergwerf/bashbeautify#14]
Could you help me understand this error and what might be causing it?  I attached the script that is causing it.  Thanks.

PS: in case it matters, I'm calling the script through a BBEdit Text Filter.
[spinpid.sh.txt](https://github.com/bergwerf/bashbeautify/files/6052373/spinpid.sh.txt)

**Comment by kyeongy** [comment]
It seems there is missing "fi" for line 280 if [[ $CPU_TEMP_SYSCTL == 2 ]]; then


________________________________

**Comment by glorious1** [comment]
Ooops, yes, guess I caught that error after I tried to beautify it.  Thank you, and thanks for the helpful script!!
