### ISSUE TITLE
Please allow customizing `tab_str` and `tab_size` in command line

### ISSUE THREAD

**Issue by brlin-tw** [hermanbergwerf/bashbeautify#8]
I'd really like to use tab as indentation and it's not possible without modifying the script if there's no command line options to specify that

**Comment by bergwerf** [comment]
We could add a `--use-tabs` and `--use-spaces` or something. I'm not sure what the recommended way is to implement this, I think its best to just match the args against the flags if the file path starts with '-' and is longer than 1.

**Comment by brlin-tw** [comment]
Seems to be implemented, closing...
