### ISSUE TITLE
Please allow not creating backup files (via command line)

### ISSUE THREAD

**Issue by brlin-tw** [hermanbergwerf/bashbeautify#9]
We use Git to version control our scripts and there's less reason to make a duplicate backup

**Comment by bergwerf** [comment]
A command line parameter might be appropriate. Also in git you could ignore backup files. The appended tilde is used by more editors such as emacs. But I agree it is a bit annoying.

**Comment by brlin-tw** [comment]
Seems to be implemented, closing...
